@expense_url={{base_url}}/groups/{{groups.kaamelott}}/expenses
@group_expense_url={{base_url}}/groups/{{groups.kaamelott}}/expenses

### GET Group Expenses - Get all expenses in a group
GET {{group_expense_url}}

### GET Group Expenses - Get all expenses from a user in a group
GET {{group_expense_url}}?paidBy=arthur

### GET Group Expenses - Get all expenses from a group, between min & max amount
GET {{group_expense_url}}?minAmount=450&maxAmount=550

### GET Group Expenses - Get all expenses from a group, by a user, between min & max amount
GET {{group_expense_url}}?paidBy=arthur&minAmount=450&maxAmount=1000

### GET Group Expenses Details - Get expenses details (how much each member owes and to whom)
GET {{group_expense_url}}/details

### POST Expense - Create an expense for 2 users (including payer)
POST {{group_expense_url}}
Content-Type: application/json

{
  "name": "Rénovation Château",
  "amount": "800.00",
  "paidByName": "arthur",
  "usersPaidFor": [
    {
      "name": "arthur",
      "amountOwed": "400.00"
    },
    {
      "name": "lancelot",
      "amountOwed": "400.00"
    }
  ]
}

### POST Expense - Create an expense for 4 users (not-including payer)
POST {{group_expense_url}}
Content-Type: application/json

{
  "name": "Fête du Printemps",
  "amount": "200.00",
  "paidByName": "arthur",
  "usersPaidFor": [
    {
      "name": "bohort",
      "amountOwed": "150.00"
    },
    {
      "name": "perceval",
      "amountOwed": "50.00"
    }
  ]
}

### POST Expense - Create an expense for 4 users (including payer)
POST {{group_expense_url}}
Content-Type: application/json

{
  "name": "Fête des Cerises",
  "amount": "500.00",
  "paidByName": "bohort",
  "usersPaidFor": [
    {
      "name": "bohort",
      "amountOwed": "200.00"
    },
    {
      "name": "arthur",
      "amountOwed": "100.00"
    },
    {
      "name": "lancelot",
      "amountOwed": "100.00"
    },
    {
      "name": "perceval",
      "amountOwed": "50.00"
    },
    {
      "name": "léodagan",
      "amountOwed": "50.00"
    }
  ]
}