@group_url={{base_url}}/groups

### GET Groups - Get all groups
GET {{group_url}}

### GET Group by ID
GET {{group_url}}/{{groups.kaamelott}}

### POST Group - Create a group as an existing User & no member
POST {{group_url}}
Content-Type: application/json

{
  "name": "Visite diplomatique en Andalousie",
  "owner": {
    "name": "Bohort",
    "email": "bohort@test.com"
  }
}

### POST Group - Create a group as a temporary user & with members
POST {{group_url}}
Content-Type: application/json

{
  "name": "Campagne contre les Visigoths",
  "owner": {
    "name": "Dagonnet"
  },
  "members": [
    {
      "name": "Arthur",
      "email": "arthur@test.com"
    },
    {
      "name": "Léodagan"
    }
  ]
}